version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
   nginx:
     image: library/alpine:latest
     ports:
       - "80:80"
     command: ['apk add python', ]
     dev_overrides:
       environment:
         - "DEBUG=1"
  
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   
